CREATE TABLE IF NOT EXISTS call_centers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  center_name VARCHAR(128) NOT NULL,
  center_slug VARCHAR(64) NOT NULL,
  center_url VARCHAR(500) NULL,
  logo_url VARCHAR(500) NULL,
  cover_image_url VARCHAR(500) NULL,
  description TEXT NULL,
  welcome_text VARCHAR(500) NULL,
  require_visitor_info TINYINT NOT NULL DEFAULT 0 COMMENT '咨询前是否要求访客登记信息：0=不需要，1=需要',
  visitor_info_required_fields JSON NULL COMMENT '访客登记必填字段配置',
  visitor_info_optional_fields JSON NULL COMMENT '访客登记选填字段配置',
  visitor_info_form_title VARCHAR(128) NULL COMMENT '访客登记弹窗标题',
  visitor_info_form_desc VARCHAR(500) NULL COMMENT '访客登记弹窗说明',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  sort_order INT NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_by_name VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_call_center_slug (center_slug),
  KEY idx_call_center_tenant_id (tenant_id),
  KEY idx_call_center_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户呼叫中心主表';