-- Migration: 060_flexisip_call_statistics
-- 为 Flexisip SIP 呼叫统计建立结构化呼叫日志表

CREATE TABLE IF NOT EXISTS flexisip_call_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  call_id_hash VARCHAR(64) NOT NULL COMMENT 'Call-ID 原文的 SHA-256 哈希',
  call_key_hash VARCHAR(64) NOT NULL COMMENT 'Call-Key 哈希（from_tag + to_tag + call_id 组合）',
  from_user VARCHAR(120) NOT NULL DEFAULT '' COMMENT '主叫用户名',
  to_user VARCHAR(120) NOT NULL DEFAULT '' COMMENT '被叫用户名',
  from_domain VARCHAR(255) NOT NULL DEFAULT '' COMMENT '主叫域',
  to_domain VARCHAR(255) NOT NULL DEFAULT '' COMMENT '被叫域',
  direction ENUM('inbound','outbound','internal','unknown') NOT NULL DEFAULT 'unknown' COMMENT '呼叫方向',
  initiated_at DATETIME NULL COMMENT '首条 INVITE 时间',
  ringing_at DATETIME NULL COMMENT '首条 180 Ringing 时间',
  answered_at DATETIME NULL COMMENT '首条 200 OK 时间',
  ended_at DATETIME NULL COMMENT 'BYE / CANCEL / 超时时间',
  estimated_duration_seconds INT UNSIGNED NULL COMMENT '信令估算时长（秒），非计费时长',
  signaling_duration_seconds INT UNSIGNED NULL COMMENT '信令持续时间（秒），从 initiated_at 到 ended_at',
  final_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '最终信令状态，如 answered / cancelled / timeout',
  final_code SMALLINT UNSIGNED NULL COMMENT '最后一个有意义的状态码',
  final_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '最后一个有意义的 reason 或警告摘要',
  result ENUM('answered','missed','cancelled','busy','declined','timeout','failed','unknown') NOT NULL DEFAULT 'unknown' COMMENT '呼叫结果',
  cancelled_by VARCHAR(32) NOT NULL DEFAULT '' COMMENT '取消者方向：caller / callee / proxy',
  source VARCHAR(64) NOT NULL DEFAULT 'flexisip' COMMENT '数据来源标识',
  warnings JSON NULL COMMENT '警告信息列表',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_call_key_hash (call_key_hash),
  INDEX idx_call_id_hash (call_id_hash),
  INDEX idx_from_user (from_user),
  INDEX idx_to_user (to_user),
  INDEX idx_direction (direction),
  INDEX idx_result (result),
  INDEX idx_initiated_at (initiated_at),
  INDEX idx_ended_at (ended_at),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Flexisip SIP 呼叫聚合摘要';


CREATE TABLE IF NOT EXISTS flexisip_call_devices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  call_log_id BIGINT UNSIGNED NULL COMMENT '关联 flexisip_call_logs.id',
  call_key_hash VARCHAR(64) NOT NULL COMMENT '关联的 call_key_hash',
  device_event_key_hash VARCHAR(64) NOT NULL COMMENT '设备事件 Key 哈希，用于唯一标识该设备参与事件',
  device_id_hash VARCHAR(64) NOT NULL COMMENT '设备 ID 的哈希，不保存原始设备 ID',
  account VARCHAR(120) NOT NULL DEFAULT '' COMMENT '注册账号',
  domain VARCHAR(255) NOT NULL DEFAULT '' COMMENT '注册域',
  role ENUM('caller','callee','unknown') NOT NULL DEFAULT 'unknown' COMMENT '设备角色',
  user_agent VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'User-Agent 头缩略值',
  transport VARCHAR(32) NOT NULL DEFAULT '' COMMENT '传输协议，如 tls / tcp / udp',
  invited_at DATETIME NULL COMMENT '该设备收到 INVITE 的时间',
  ringing_at DATETIME NULL COMMENT '该设备开始振铃的时间',
  answered_at DATETIME NULL COMMENT '该设备应答的时间',
  ended_at DATETIME NULL COMMENT '该设备通话结束的时间',
  final_code SMALLINT UNSIGNED NULL COMMENT '该设备最后一个状态码',
  final_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '该设备最后一个 reason 摘要',
  result ENUM('answered','missed','cancelled','declined','busy','timeout','failed','unknown') NOT NULL DEFAULT 'unknown' COMMENT '该设备的结果',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_device_event_key_hash (device_event_key_hash),
  INDEX idx_call_key_hash (call_key_hash),
  INDEX idx_account_domain (account, domain),
  INDEX idx_role (role),
  INDEX idx_result (result),
  INDEX idx_created_at (created_at),
  CONSTRAINT fk_call_devices_call_log FOREIGN KEY (call_log_id) REFERENCES flexisip_call_logs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Flexisip 呼叫设备/分支参与记录';


CREATE TABLE IF NOT EXISTS flexisip_call_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_key_hash VARCHAR(64) NOT NULL COMMENT '事件 Key 哈希（from_tag + cseq + method 组合），唯一标识一个 SIP 事务事件',
  call_key_hash VARCHAR(64) NOT NULL COMMENT '关联的 call_key_hash',
  event_time DATETIME NOT NULL COMMENT '事件发生时间',
  event_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '事件类型，如 invite / ringing / answer / bye / cancel / timeout',
  method VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'SIP Method，如 INVITE / BYE / CANCEL',
  status_code SMALLINT UNSIGNED NULL COMMENT 'SIP 状态码',
  reason_phrase VARCHAR(120) NOT NULL DEFAULT '' COMMENT 'Reason 短语或 Q.850 原因',
  from_user VARCHAR(120) NOT NULL DEFAULT '' COMMENT '主叫用户名',
  from_domain VARCHAR(255) NOT NULL DEFAULT '' COMMENT '主叫域',
  to_user VARCHAR(120) NOT NULL DEFAULT '' COMMENT '被叫用户名',
  to_domain VARCHAR(255) NOT NULL DEFAULT '' COMMENT '被叫域',
  cseq_number INT UNSIGNED NULL COMMENT 'CSeq 序号',
  cseq_method VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'CSeq Method',
  from_tag_hash VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'From tag 的 SHA-256 哈希',
  to_tag_hash VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'To tag 的 SHA-256 哈希',
  branch_hash VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Via branch 参数的 SHA-256 哈希',
  user_agent VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'User-Agent 缩略值',
  raw_event_hash VARCHAR(64) NOT NULL DEFAULT '' COMMENT '原始事件字符串的 SHA-256 哈希，用于去重和溯源',
  source VARCHAR(64) NOT NULL DEFAULT 'flexisip' COMMENT '数据来源标识',
  warnings JSON NULL COMMENT '事件处理警告',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_event_key_hash (event_key_hash),
  INDEX idx_call_key_hash (call_key_hash),
  INDEX idx_event_time (event_time),
  INDEX idx_event_type (event_type),
  INDEX idx_method (method),
  INDEX idx_status_code (status_code),
  INDEX idx_from_user (from_user),
  INDEX idx_to_user (to_user),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Flexisip SIP 信令事件脱敏摘要';
